apiVersion: v1
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"Username\":\"%s\",\"Password\":\"%s\",\"Email\":\"some@bogus.email\"}}}" .Values.image.imagePullSecret.registry .Values.image.imagePullSecret.username .Values.image.imagePullSecret.password | b64enc }}
kind: Secret
metadata:
  name: {{ include "cicd-example.name" . }}-imagepull
type: kubernetes.io/dockerconfigjson